Update .gitlab-ci.yml

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,3 +1,6 @@
+image: docker:stable
+
+
 # Define the sequence of stages for job execution
 stages:
   - compile
@@ -5,6 +8,7 @@ stages:
   - release
   - launch
 
+# Backend Compilation
 compile-backend:
   stage: compile
   tags:
@@ -12,12 +16,14 @@ compile-backend:
   image: maven:latest
   script:
     - cd Backend
+    - pwd
+    - ls
     - mvn clean package
-    
   artifacts:
     paths:
       - Backend/target/*.jar
 
+# Frontend Compilation
 compile-frontend:
   stage: compile
   tags:
@@ -25,6 +31,8 @@ compile-frontend:
   image: node:18-alpine
   script:
     - cd Frontend
+    - pwd
+    - ls
     - npm install
     - echo $BASE_URL
     - export BACKEND_BASE_URL=$BASE_URL
@@ -34,55 +42,72 @@ compile-frontend:
     paths:
       - Frontend/build
 
+# Backend Docker Image Release
 release-backend:
-  image: docker:latest
+  image: docker:stable
   stage: release
   tags:
     - Neighbourly-runner
   variables:
     DOCKER_TLS_CERTDIR: ""
-    DOCKER_HOST: "tcp://docker:2375"
   services:
-    - docker:dind
+   - name: docker:24.0-dind
+     alias: docker
+  before_script:
+   - sleep 30  # Adjust the duration as needed
+   - docker info  # Verify Docker is accessible
   script:
+    - nslookup docker || echo "DNS lookup failed"
     - cd Backend
     - pwd
     - ls
     - echo $SERVER_IP
     - docker --version
-    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PWD docker.io
+    - echo $DOCKER_HUB_PWD | docker login --username $DOCKER_HUB_USER --password-stdin docker.io
     - IMAGE_TAG="$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA"
-    - docker build -t keshvigodhani/backend-api:$IMAGE_TAG . -f Dockerfile
-    - docker push keshvigodhani/backend-api:$IMAGE_TAG
+    - docker build -t $DOCKER_HUB_USER/backend-api:$IMAGE_TAG . -f Dockerfile
+    - docker push $DOCKER_HUB_USER/backend-api:$IMAGE_TAG
+    - echo "Docker image pushed successfully!"
   only:
-    - cicd_issue26
+    - cicd_fix
     - dev
     - main
+
+
+# Frontend Docker Image Release
+# check
 release-frontend:
-  image: docker:latest
+  image: docker:stable
   stage: release
   tags:
     - Neighbourly-runner
   variables:
     DOCKER_TLS_CERTDIR: ""
-    DOCKER_HOST: "tcp://docker:2375"
   services:
-    - docker:dind
+    - name: docker:24.0-dind
+      alias: docker
+  before_script:
+    - sleep 30  # Adjust the duration as needed
+    - docker info  # Verify Docker is accessible
   script:
+    - nslookup docker || echo "DNS lookup failed"
     - cd Frontend
     - pwd
     - ls
     - echo $SERVER_IP
     - docker --version
-    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PWD docker.io
+    - echo $DOCKER_HUB_PWD | docker login --username $DOCKER_HUB_USER --password-stdin docker.io
     - IMAGE_TAG="$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA"
-    - docker build --build-arg BACKEND_BASE_URL=$BASE_URL -t keshvigodhani/frontend:$IMAGE_TAG . -f Dockerfile
-    - docker push keshvigodhani/frontend:$IMAGE_TAG
+    - docker build --build-arg BACKEND_BASE_URL=$BASE_URL -t $DOCKER_HUB_USER/frontend:$IMAGE_TAG . -f Dockerfile
+    - docker push $DOCKER_HUB_USER/frontend:$IMAGE_TAG
+    - echo "Frontend Docker image pushed successfully!"
   only:
-    - cicd_issue26
+    - cicd_fix
     - dev
     - main
 
+
+# Backend Deployment
 launch-backend:
   image: alpine:latest
   stage: launch
@@ -122,16 +147,18 @@ launch-backend:
           ;;
       esac
     - ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PWD docker.io"
-    - ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker pull keshvigodhani/backend-api:$IMAGE_TAG"
+    - ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker pull $DOCKER_HUB_USER/backend-api:$IMAGE_TAG"
     - ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker stop $CONTAINER_NAME || true && docker container rm -f $CONTAINER_NAME || true"
-    - ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker run -d -p $SERVER_PORT:$SERVER_PORT --name $CONTAINER_NAME --restart=always -e SERVER_PORT=$SERVER_PORT -e SPRING_DATASOURCE_URL=$DB_URL -e SPRING_DATASOURCE_USERNAME=$DB_USER -e SPRING_DATASOURCE_PASSWORD=$DB_PASSWORD -e EMAIL_HOST=$EMAIL_HOST -e EMAIL_PORT=$EMAIL_PORT -e EMAIL_USERNAME=$EMAIL_USERNAME -e EMAIL_PASSWORD=$EMAIL_PASSWORD -e FRONTEND_HOST=$FRONTEND_HOST -e FRONTEND_LOGIN_URL=$FRONTEND_LOGIN_URL -e FRONTEND_UPDATE_PASSWORD_URL=$FRONTEND_UPDATE_PASSWORD_URL keshvigodhani/backend-api:$IMAGE_TAG"
+    - ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker run -d -p $SERVER_PORT:$SERVER_PORT --name $CONTAINER_NAME --restart=always -e SERVER_PORT=$SERVER_PORT -e SPRING_DATASOURCE_URL=$DB_URL -e SPRING_DATASOURCE_USERNAME=$DB_USER -e SPRING_DATASOURCE_PASSWORD=$DB_PASSWORD -e EMAIL_HOST=$EMAIL_HOST -e EMAIL_PORT=$EMAIL_PORT -e EMAIL_USERNAME=$EMAIL_USERNAME -e EMAIL_PASSWORD=$EMAIL_PASSWORD -e FRONTEND_HOST=$FRONTEND_HOST -e FRONTEND_LOGIN_URL=$FRONTEND_LOGIN_URL -e FRONTEND_UPDATE_PASSWORD_URL=$FRONTEND_UPDATE_PASSWORD_URL $DOCKER_HUB_USER/backend-api:$IMAGE_TAG"
   environment:
     name: development
     url: http://$SERVER_IP:$SERVER_PORT
   only:
-    - cicd_issue26
+    - cicd_fix
     - dev
     - main
+
+# Frontend Deployment
 launch-frontend:
   image: alpine:latest
   stage: launch
@@ -151,27 +178,27 @@ launch-frontend:
         dev)
           CONTAINER_NAME="neighbourly-dev-app-frontend"
           SERVER_PORT=3000
-          REACT_APP_BACKEND_BASE_URL=$DEV_BACKEND_BASE_URL
+          REACT_APP_API_BASE_URL=$DEV_BACKEND_BASE_URL
           ;;
         main)
           CONTAINER_NAME="neighbourly-prod-app-frontend"
           SERVER_PORT=3080
-          REACT_APP_BACKEND_BASE_URL=$PROD_BACKEND_BASE_URL
+          REACT_APP_API_BASE_URL=$PROD_BACKEND_BASE_URL
           ;;
         *)
           CONTAINER_NAME="neighbourly-test-app-frontend"
           SERVER_PORT=3030
-          REACT_APP_BACKEND_BASE_URL=$TEST_BACKEND_BASE_URL
+          REACT_APP_API_BASE_URL=$TEST_BACKEND_BASE_URL
           ;;
       esac
     - ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PWD docker.io"
-    - ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker pull keshvigodhani/frontend:$IMAGE_TAG"
+    - ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker pull $DOCKER_HUB_USER/frontend:$IMAGE_TAG"
     - ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker container rm -f $CONTAINER_NAME || true"
-    - ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker run -d -p $SERVER_PORT:$SERVER_PORT -e PORT=$SERVER_PORT -e REACT_APP_BACKEND_BASE_URL=$REACT_APP_BACKEND_BASE_URL --name $CONTAINER_NAME --restart=always keshvigodhani/frontend:$IMAGE_TAG"
+    - ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker run -d -p $SERVER_PORT:$SERVER_PORT -e PORT=$SERVER_PORT -e REACT_APP_API_BASE_URL=$REACT_APP_API_BASE_URL --name $CONTAINER_NAME --restart=always $DOCKER_HUB_USER/frontend:$IMAGE_TAG"
   environment:
     name: development
     url: http://$SERVER_IP:$SERVER_PORT
   only:
-    - cicd_issue26
+    - cicd_fix
     - dev
     - main
